### ISSUE TITLE
need build instructions for popular dists

### ISSUE THREAD

**Issue by YurySolovyov** [Arakis/gcaliper#1]
it is too comfusing to build otherwise

**Comment by arakis** [comment]
Normally, `make` or `make install` should do the work. Maybe you are missing dependencies. And, in the commits of the last days, i moved from gtk2 to gtk3, so you need gtk-sharp3 ( https://github.com/mono/gtk-sharp ).

So, wich distro are you using or, what problems do you have exactly?

**Comment by YurySolovyov** [comment]
Ubuntu 14.04
Error output:

```
~/gcaliper$ make
xbuild solution.sln
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 6/15/2015 5:47:09 PM.
__________________________________________________
Project "/home/user/gcaliper/solution.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
: error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.
    Task "Message" execution -- FAILED
    Done building target "ValidateSolutionConfiguration" in project "/home/user/gcaliper/solution.sln".-- FAILED
Done building project "/home/user/gcaliper/solution.sln".-- FAILED

Build FAILED.
Errors:

/home/user/gcaliper/solution.sln (default targets) ->
(ValidateSolutionConfiguration target) ->

    : error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.

     0 Warning(s)
     1 Error(s)

Time Elapsed 00:00:00.2018170
make: *** [compile] Error 1

```

I tried to install some mono deps, but they were too big, so I aborted it

**Comment by arakis** [comment]
Thank you for your feedback. I will setup a ubuntu-gnome 15.04 virtual machine and test the scenario today.

**Comment by YurySolovyov** [comment]
One more question: I understand, that as developer you are trying to reuse some code from mono and gtk, but I'm curious: how many libs I need to install on fresh system to get it running? Installing all mono and gtk dev libs just seems wrong...
Maybe it is possible to somehow statically link them, so you just need to download just one binary?

**Comment by arakis** [comment]
This is no c++, it's uses a runtime environment. For example, when you are using python, you have lots of dependencies, too, and you cannot compile it to a native image, too. So, see mono "like" python, but a way more complex.

I tested is now successfully on my machine. Simple install the dependencies, dont worry about the 250 MB installed size:

```
sudo apt-get install mono-complete gtk-sharp3
```

and call `make` again.

(tested on ubuntu-gnome 15.04)

**Comment by arakis** [comment]
i've updated the readme

**Comment by YurySolovyov** [comment]
Thanks, will try this tomorrow!

**Comment by YurySolovyov** [comment]
Works!

**Comment by arakis** [comment]
Greate! If you have any suggestions, please let me know.
